install.packages("xlsx")
install.packages("reshape2")
install.packages("ggplot2")
install.packages("GGally")
install.packages("vcd")
install.packages("glmnet")
install.packages("devtools")
install.packages("leaps")
install.packages("gam")
install.packages("tree")
install.packages('randomForest')
install.packages('party')
install.packages('rgdal')
install.packages('scales')
install.packages('ggmap')
install.packages('dplyr')
install.packages('Cairo')
install.packages('maptools')


