---
title: "Simulation tests"
output:
  html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      warning=FALSE, message=FALSE)
knitr::opts_knit$set(root.dir="../")
```

```{r constansts}
library(MLlibrary)
library(ggplot2)
library(dplyr)
#library(doMC)
#registerDoMC(cores=3)
K = 5
```

```{r data_generation}
gaussian <- function(mean, sd) {
  function(response) {response + rnorm(length(response), mean=mean, sd=sd)}
}

linear_ <- function(nvar=10, nrow=100) {
  variables <- as.character(seq_len(nvar))
  coefficients <- seq_along(variables)
  X <- matrix(rnorm(nvar * nrow), nrow=nrow, ncol=nvar)
  y <- 2 * (X %*% coefficients) + 10
  list(y=y, X=X)
}

linear <- function(nvar=10, nrow=100, noise=function(response) {response}) {
  d <- linear_(nvar, nrow)
  d$y <- noise(d$y)
  d
}

exponential <- function(nvar=10, nrow=100) {
 d <- linear_(nvar, nrow)
 d$y <- exp(d$y / 20)
 d
}

cuts_ <- function(nvar=10, nrow=100) {
  X <- matrix(rnorm(nvar * nrow), nrow=nrow, ncol=nvar)
  cuts <- rnorm(nvar)
  cuts <- matrix(cuts, nrow=nrow, ncol=nvar, byrow = TRUE)
  X_transformed <- X<cuts
  variables <- as.character(seq_len(nvar))
  coefficients <- seq_along(variables)
  y <- as.vector(2 * (X_transformed %*% coefficients) + 10)
  list(y=y, X=X)
}

cuts <- function(nvar=10, nrow=100, noise=function(response) {response}) {
  d <- cuts_(nvar, nrow)
  d$y <- noise(d$y)
  d
}

cuts_and_linear_ <- function(nvar=10, nrow=100, alpha=0.5) {
  X <- matrix(rnorm(nvar * nrow), nrow=nrow, ncol=nvar)
  cuts <- rnorm(nvar)
  cuts <- matrix(cuts, nrow=nrow, ncol=nvar, byrow = TRUE)
  X_transformed <- X<cuts
  variables <- as.character(seq_len(nvar))
  coefficients <- seq_along(variables)
  y <- 2*(alpha*as.vector((X_transformed %*% coefficients) + (1-alpha)*(X %*% coefficients))) + 10
  list(y=y, X=X)
}

cuts_and_linear <- function(nvar=10, nrow=100, alpha = 0.5, noise=function(response) {response}) {
  d <- cuts_and_linear_(nvar, nrow, alpha)
  d$y <- noise(d$y)
  d
}
```

```{r model_running}
run_linear <- function(ksplit) {
  ls <- kfold_(LeastSquares(), ksplit)
  ridge <- kfold_(Ridge(), ksplit)
  lasso <- kfold_(Lasso(), ksplit)
  join_dfs(list(ls=ls, ridge=ridge, lasso=lasso))
}

run_trees <- function(ksplit, ksplit_nmm) {
  rtree <- kfold_(rTree2(), ksplit_nmm)
  rforest <- kfold_(Forest(), ksplit)
  btrees <- kfold_(BoostedTrees(n.trees=500), ksplit_nmm)
  btrees_laplace <- kfold_(BoostedTrees(n.trees=500, distribution="laplace"), ksplit_nmm)
  join_dfs(list(rtree=rtree, rforest=rforest, btrees=btrees, btrees_laplace=btrees_laplace))
}

run_all_linear <- function(dataset) {
  X <- dataset$X
  y <- dataset$y
  ksplit <- kfold_split(K, y, X, seed=1)
  linears <- run_linear(ksplit)
  linears
}

run_all <- function(dataset, ix=TRUE) {
  X <- dataset$X
  y <- dataset$y
  ksplit <- kfold_split(K, y, X, seed=1)
  ksplit_nmm <- kfold_split(K, y, data.frame(X), seed=1)
  linears <- run_linear(ksplit)
  trees <- run_trees(ksplit, ksplit_nmm)
  joined <- rbind(linears, filter(trees, method != "true"))
  
  if (ix) {
    X_ix <- model.matrix(y ~ . + .:., data=data.frame(y=y, X))
    ksplit_ix <- kfold_split(K, y, X_ix, seed=1)
    ksplit_nmm_ix <- kfold_split(K, y, data.frame(X_ix), seed=1)
    linears_ix <- run_linear(ksplit_ix)
    trees_ix <- run_trees(ksplit_ix, ksplit_nmm_ix)
    joined_ix <- rbind(linears_ix, trees_ix)
    joined_ix <- filter(joined_ix, method != "true")
    joined_ix <- mutate(joined_ix, method=paste(method, "ix", sep="_"))
    joined <- rbind(joined, filter(joined_ix, method != "true"))
  }
  joined
}

plot_all <- function(res) {
  ix <- nrow(filter(res, grepl("_ix", method))) > 0
  res_ix <- filter(res, grepl("_ix", method) | method == "ls")
  res <- filter(res, !grepl("_ix", method))
  
#   plot(plot_accuracy_(res) + scale_color_brewer(palette="Set2"))
#   if (ix) {
#     plot(plot_accuracy_(res_ix) + scale_color_brewer(palette="Set2"))
#   }
  
  plot(plot_accuracy_(res, THRESHOLD=0.3) + scale_color_brewer(palette="Set2"))
  if (ix) {
    plot(plot_accuracy_(res_ix, THRESHOLD=0.3) + scale_color_brewer(palette="Set2"))
  }
  
  plot(plot_accuracy_(res, THRESHOLD=0.3, BASE="ls") + scale_color_brewer(palette="Set2"))
  if (ix) {
    plot(plot_accuracy_(res_ix, THRESHOLD=0.3, BASE="ls") + scale_color_brewer(palette="Set2"))
  }
}

```

## Linear Data

### No noise
```{r linear_no_noise}
dataset <- linear(nvar=10, nrow=1000)
res <- run_all(dataset)
plot_all(res)
```

## Linear + Zero Mean Gaussian

### +10%
```{r gaussian_10}
noise <- gaussian(0, 1)
dataset <- linear(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```

### +50%
```{r gaussian_50}
noise <- gaussian(0, 5)
dataset <- linear(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```


### +90%
```{r gaussian_90}
noise <- gaussian(0, 9)
dataset <- linear(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```

### Heteroskedasticity

```{r heteroskedasticity}
noise <- function(response) {
  rnorm(length(response), mean=response, sd=abs(response / 10))
}
dataset <- linear(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```

## Lognormal noise

### Mean 0

```{r lognormal}
noise <- function(response) {
  response + rlnorm(length(response), meanlog=0, sdlog=3)
}
dataset <- linear(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```

### Heteroskedastic lognormal
```{r lognormal_het}
noise <- function(response) {
  response + rlnorm(length(response), meanlog=0, sdlog=abs(response / 10))
}
dataset <- linear(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```

## Wide
```{r wide}
dataset <- linear(nvar=500, nrow=100)
res <- run_all(dataset, ix=FALSE)
plot_all(res)
```


## Extraneous
```{r extraneous}
dataset <- linear(nvar=10, nrow=500)
dataset$X <- cbind(matrix(rnorm(1000 * 500, mean=10, sd=5), nrow=500, ncol=1000), dataset$X)
res <- run_all(dataset, ix=FALSE)
plot_all(res)
```

## Exponential data
```{r exponential}
dataset <- exponential(nvar=10, nrow=1000)
res <- run_all(dataset)
plot_all(res)
```

## Cuts data
```{r cuts}
dataset <- cuts(nvar=10, nrow=1000)
res <- run_all(dataset)
plot_all(res)
```

## Cuts data + Gaussian 50%
```{r cuts+noise}
noise <- gaussian(0, 5)
dataset <- cuts(nvar=10, nrow=1000, noise=noise)
res <- run_all(dataset)
plot_all(res)
```

## 0.3 Cuts + 0.7 linear data
```{r cuts + linear 0.3}
  dataset <- cuts_and_linear(nvar=10, nrow=1000, alpha=0.3)
  res <- run_all(dataset)
  plot_all(res)
```

## 0.7 Cuts + 0.3 linear data
```{r cuts + linear 0.7}
dataset <- cuts_and_linear(nvar=10, nrow=1000, alpha=0.7)
res <- run_all(dataset)
plot_all(res)
```
